### ISSUE TITLE
Length of time onscreen

### ISSUE THREAD

**Issue by kierobinson1** [cameronehrlich/CEMovieMaker#2]
Hi!
I'm having a problem with changing the length of time that each image stays on the screen. For example I'd like the user to choose an amount of time, in seconds, and the image would be on the screen for that length of time. I've tried changing the _frameTime variable, but to no avail. It's set default to CMTimeMake(1,1) which places each image on the screen for 1 second. However if I change it to another number, such as   _frameTime = CMTimeMake(10, 2); this should show each image for 5 seconds, however it only applies to the first image, then the rest of the images are shown for a minimal length of time.

Thanks
Kieran

**Comment by jathu** [comment]
Hey Kieran, if you are still having that problem (or anyone in the future), this issue is caused by lines [82-84](https://github.com/cameronehrlich/CEMovieMaker/blob/master/CEMovieMaker/CEMovieMaker.m#L82-L84). If you log the seconds of presentTime, you can see that the frames are all 5 seconds. However they would be incremented by the maximum time, the timescale.

The solution I came up with:

``` objective-c
    NSInteger frameNumber = [images count];
    // Modified to fix frame length
    int singleFrameMultiplier = 10000;
    int singleFrameTime = ((float)self.frameTime.value/frameNumber)*singleFrameMultiplier;

    [self.writerInput requestMediaDataWhenReadyOnQueue:mediaInputQueue usingBlock:^{
        while (YES){
            if (i >= frameNumber) {
                break;
            }
            if ([self.writerInput isReadyForMoreMediaData]) {

                CVPixelBufferRef sampleBuffer = [self newPixelBufferFromCGImage:[[images objectAtIndex:i] CGImage]];

                if (sampleBuffer) {
                    if (i == 0) {
                        [self.bufferAdapter appendPixelBuffer:sampleBuffer withPresentationTime:kCMTimeZero];
                    } else {
                        // Modified to fix frame length
                        CMTime frameTime = CMTimeMake(i * singleFrameTime, singleFrameMultiplier);
                        // NSLog(@"i: %d -> second: %f", i, CMTimeGetSeconds(frameTime));
                        [self.bufferAdapter appendPixelBuffer:sampleBuffer withPresentationTime:frameTime];
                    }
                    CFRelease(sampleBuffer);
                    i++;
                }
            }
        }
```

CMTime is a bit weird and confusing to wrap your head around, I suggest you read [this](http://stackoverflow.com/a/6303604/2287993). `self.frameTime.value` is the intended length of the whole movie, where as the frameNumber is simply total number of frames. We then construct the CMTime to give each frame the specific time so it fits into within the `self.frameTime.value` limit. The reason we are using a multiplier of 10000 is just arbitrary. You can choose any multiple of 10. Remember in CMTimeMake(value, timeScale), value/timeScale = seconds. As it doest not accept floats, we adjust it with the modifier.

You should be able to modify this to fit your scenario.

Edit:

If you want to set the intended duration, you simply set the `self.frameTime`.

``` objective-c
self.frameTime = CMTimeMake(duration, 1);
```

**Comment by cameronehrlich** [comment]
:+1:
